ALTER TABLE crime_reports
ADD COLUMN police_id VARCHAR(255) DEFAULT NULL,
ADD COLUMN case_taken_at TIMESTAMP DEFAULT NULL;

CREATE TABLE IF NOT EXISTS case_updates (
  id INT(11) NOT NULL AUTO_INCREMENT,
  report_id INT(11) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  action VARCHAR(50) NOT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  details TEXT,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;